name: SwiftGenSample
options:
  xcodeVersion: "14.0"
  deploymentTarget:
    iOS:  "14.0"
  developmentLanguage: en
#  postGenCommand: rbenv exec bundle exec pod install

settings:
  base:
    SWIFT_VERSION: 5.0

targets:
  SwiftGenSample:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: $TARGET_NAME
        PRODUCT_BUNDLE_IDENTIFIER: com.github.droibit.${PRODUCT_NAME}
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        ENABLE_PREVIEWS: true
    sources:
      - path: .
      - path: ./App/iOS

schemes:
  SwiftGenSample:
    build:
      targets:
        SwiftGenSample: all
    run:
      config: Debug
    test:
      config: Debug
    profile: 
      config: Debug
    analyze:
      config: Debug
    archive: 
      config: Debug